#!/usr/bin/env python

import argparse
import tomllib

import requests
from packaging.specifiers import SpecifierSet

parser = argparse.ArgumentParser(description='Get supported Python releases')
parser.add_argument('repo', type=str, help='repository name')
parser.add_argument('-v', '--version', type=str, help='package version')

args = parser.parse_args()

# List of maintained Python releases. Update this once a year when a new
# release is available (usually early October).
VERSIONS = ('3.9', '3.10', '3.11', '3.12', '3.13')

URL = 'https://raw.githubusercontent.com/{repo}/refs/tags/{version}/pyproject.toml'

response = requests.get(URL.format(repo=args.repo, version=args.version))
response.raise_for_status()

project = tomllib.loads(response.text)['project']
supported_versions = SpecifierSet(project['requires-python']).filter(VERSIONS)
print(['cp' + v.replace('.', '') for v in supported_versions])
