#!/usr/bin/env python

import argparse
import tomllib

import requests
from packaging.specifiers import SpecifierSet

# List of maintained Python releases. Update this once a year when a new
# release is available (usually early October).
VERSIONS = ('3.9', '3.10', '3.11', '3.12', '3.13')

URL = 'https://raw.githubusercontent.com/{repo}/refs/tags/{version}/{file}'


def main(repo, version, use_setup_py=False):
    file = 'setup.py' if use_setup_py else 'pyproject.toml'
    response = requests.get(URL.format(repo=repo, version=version, file=file))
    response.raise_for_status()

    if use_setup_py:
        line = next(l for l in response.text.splitlines() if 'python_requires' in l)
        requires = line.split('=', 1)[1].strip().strip('\'",')
    else:
        requires = tomllib.loads(response.text)['project']['requires-python']

    supported_versions = SpecifierSet(requires).filter(VERSIONS)
    return ['cp' + v.replace('.', '') for v in supported_versions]


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Get supported Python releases')
    parser.add_argument('repo', type=str, help='repository name')
    parser.add_argument('-v', '--version', type=str, help='package version')
    parser.add_argument(
        '--use-setup-py',
        action='store_true',
        help='use setup.py instead of pyproject.toml',
    )

    args = parser.parse_args()
    print(main(args.repo, args.version, args.use_setup_py))
