name: Build wheels

on:
  workflow_dispatch:
  schedule:
    - cron: "15 22 * * 0" # 22.15 UTC every Sunday

permissions:
  contents: write

jobs:
  mkl-service:
    uses: ./.github/workflows/wheels.yml
    with:
      name: mkl-service
      repo: IntelPython/mkl-service
      manylinux: true

  numpy:
    uses: ./.github/workflows/wheels.yml
    with:
      name: numpy
      repo: numpy/numpy
      manylinux: true
    needs: mkl-service

  scipy:
    uses: ./.github/workflows/wheels.yml
    with:
      name: scipy
      repo: scipy/scipy
      manylinux: true
    needs: [mkl-service, numpy]
