name: Rebuild scipy

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scipy:
    uses: ./.github/workflows/wheels.yml
    with:
      name: scipy
      repo: scipy/scipy
      force-build: true
      # version: 2.1.3
