name: Rebuild numpy

on:
  workflow_dispatch:

permissions: {}

jobs:
  numpy:
    uses: ./.github/workflows/wheels.yml
    permissions:
      contents: write
    with:
      name: numpy
      repo: numpy/numpy
      force-build: true
      # version: 2.5.1
