name: Rebuild scipy

on:
  workflow_dispatch:

permissions: {}

jobs:
  scipy:
    uses: ./.github/workflows/wheels.yml
    permissions:
      contents: write
    with:
      name: scipy
      repo: scipy/scipy
      force-build: true
      # version: 1.18.0
