name: Rebuild all

on:
  workflow_dispatch:

permissions: {}

jobs:
  mkl-service:
    uses: ./.github/workflows/wheels.yml
    permissions:
      contents: write
    with:
      name: mkl-service
      repo: IntelPython/mkl-service
      force-build: true

  numpy:
    uses: ./.github/workflows/wheels.yml
    permissions:
      contents: write
    with:
      name: numpy
      repo: numpy/numpy
      force-build: true
    needs: mkl-service

  scipy:
    uses: ./.github/workflows/wheels.yml
    permissions:
      contents: write
    with:
      name: scipy
      repo: scipy/scipy
      force-build: true
    needs: [mkl-service, numpy]
