name: Build wheels

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/wheels.yml
    with:
      name: mkl-service
      repo: IntelPython/mkl-service
      # name: numpy
      # repo: numpy/numpy
