name: Wheels

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
        description: 'Package to build (numpy, scipy)'
      force-build:
        required: false
        type: boolean
        description: 'Force build even if wheels exist'

jobs:
  version:
    runs-on: ubuntu-latest

    outputs:
      package: ${{ env.VERSION }}
      python: ${{ env.PY_VERSIONS }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.x
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Get latest release and supported Python versions
        run: |
          REPO="${{ inputs.package }}/${{ inputs.package }}"
          URL="https://api.github.com/repos/${REPO}/releases/latest"
          VERSION="$(curl -s "${URL}" | jq -r '.tag_name')"
          echo "VERSION=${VERSION}" >>$GITHUB_ENV
          echo "PY_VERSIONS=$(uv run tools/py_versions ${REPO} -v ${VERSION})" >>$GITHUB_ENV

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        # os: [ubuntu-22.04, windows-2019]
        python: ${{ fromJson(needs.version.outputs.python) }}

    name: ${{ inputs.package }}-${{ matrix.python }} (${{ matrix.os }})

    needs: version

    runs-on: ${{ matrix.os }}

    continue-on-error: true

    defaults:
      run:
        shell: bash

    steps:
      - name: Set environment variables
        run: |
          echo "UV_PYTHON=${{ matrix.python }}" >>$GITHUB_ENV
          echo "UV_PYTHON_PREFERENCE=only-managed" >>$GITHUB_ENV

          echo "SRC_DIR=${{ github.workspace }}/src" >>$GITHUB_ENV
          cd ../.. && echo "MKL_DIR=$(pwd)/mkl" >>$GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.x
          enable-cache: false

      - name: Install pkg-config (Windows)
        run: |
          choco install -y --no-progress --stoponfirstfailure \
              --checksum 6004DF17818F5A6DBF19CB335CC92702 pkgconfiglite
        if: runner.os == 'windows'

      - name: Install gcc (Windows)
        run: |
          choco install rtools -y --no-progress --force --version=4.0.0.20220206
          echo "c:\rtools40\ucrt64\bin;" >>$GITHUB_PATH
        if: runner.os == 'windows' && inputs.package == 'scipy'

      - name: Install MKL libraries
        run: |
          export VIRTUAL_ENV="${{ env.MKL_DIR }}"
          uv venv "${VIRTUAL_ENV}"
          uv pip install mkl-devel

          # Get MKL version.
          echo "MKL_VERSION=$(uv pip show mkl | grep '^Version' | sed 's/Version: //')" \
              >>$GITHUB_ENV

          # Get pkg-config path.
          case "${{ runner.os }}" in
            Linux) source "${VIRTUAL_ENV}"/bin/activate ;;
            Windows) source "${VIRTUAL_ENV}"/Scripts/activate ;;
          esac
          echo "PKG_CONFIG_PATH=$(python tools/get_file_in_pkg.py mkl-sdl.pc \
              --pkg mkl-devel --parent)" >>$GITHUB_ENV

          # Fetch MKL license.
          cat $(python tools/get_file_in_pkg.py LICENSE.txt --pkg mkl-devel) \
              >>"${{ github.workspace }}/patches/LICENSE_MKL.txt"

      - name: Check out source
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.package}}/${{ inputs.package }}
          ref: ${{ needs.version.outputs.package }}
          path: ${{ env.SRC_DIR }}
          submodules: recursive

      - name: Add MKL to runtime dependencies
        working-directory: ${{ env.SRC_DIR }}
        run: |
          # Pin runtime library to the exact version used for compiling.
          uv add --no-sync mkl=="${MKL_VERSION}" mkl-service

      - name: Add MKL licence
        working-directory: ${{ env.SRC_DIR }}
        run: |
          echo "" >>LICENSE.txt
          echo "----" >>LICENSE.txt
          echo "" >>LICENSE.txt
          cat LICENSES_bundled.txt >>LICENSE.txt
          cat "${{ github.workspace }}/patches/LICENSE_MKL.txt" >>LICENSE.txt

      - name: Apply patches
        run: |
          # Apply patches
          cd "${{ env.SRC_DIR }}"
          git apply "${{ github.workspace }}"/patches/${{ inputs.package }}/*.patch

          # Fix MKL pkg-config on Windows
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp "${{ github.workspace }}"/patches/mkl/*.pc "${PKG_CONFIG_PATH}/"
          fi

      # TODO: add link time optimization flags once everything is working (-Db_lto)
      - name: Build wheel
        working-directory: ${{ env.SRC_DIR }}
        run: |
          case "${{ inputs.package }}" in
            numpy)
              flags="-Csetup-args=-Dblas=mkl-sdl \
                     -Csetup-args=-Dlapack=mkl-sdl \
                     -Csetup-args=-Dallow-noblas=false"
              [[ "${{ runner.os }}" == "Windows" ]] && flags="${flags} -Csetup-args=--vsenv"
              ;;
            scipy)
              # MSVC is unable to compile Pythran, use gcc or set -Duse-pythran=false.
              flags="-Csetup-args=-Dblas=mkl-sdl \
                     -Csetup-args=-Dlapack=mkl-sdl \
                     -Csetup-args=-Duse-g77-abi=true"
              ;;
          esac
          uv build --wheel --index https://urob.github.io/numpy-mkl ${flags}

      - name: Repair wheel (Linux)
        run: |
          mkdir -p wheelhouse
          uvx auditwheel repair "${{ env.SRC_DIR }}"/dist/*.whl -w wheelhouse \
              --exclude 'libmkl*' --plat manylinux_2_35_x86_64
        if: runner.os == 'linux'

      - name: Repair wheel (Windows)
        run: |
          mkdir -p wheelhouse
          uvx delvewheel repair "${{ env.SRC_DIR }}"/dist/*.whl -w wheelhouse \
              --exclude mkl_rt.2.dll --exclude libsf_error_state.dll
        if: runner.os == 'windows'

      - name: Run tests
        run: |
          # Make sure we don't pick up the development MKL libraries.
          rm -rf "${{ env.MKL_DIR }}"

          # Set up test environment.
          export VIRTUAL_ENV="testenv"
          uv venv "${VIRTUAL_ENV}"
          case "${{ inputs.package }}" in
            numpy)
              uv pip install -r "${{ env.SRC_DIR }}"/requirements/test_requirements.txt
              uv pip install threadpoolctl
              ;;
            scipy)
              uv pip install -r "${{ env.SRC_DIR }}"/requirements/test.txt \
                  --index https://urob.github.io/numpy-mkl
              ;;
          esac
          uv pip install wheelhouse/*.whl

          case "${{ runner.os }}" in
            Linux) source "${VIRTUAL_ENV}"/bin/activate ;;
            Windows) source "${VIRTUAL_ENV}"/Scripts/activate ;;
          esac
          case "${{ inputs.package }}" in
            numpy) python tools/numpy_tests.py ;;
            scipy) python -c 'import sys; import scipy; sys.exit(not scipy.test())' ;;
          esac

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package }}-${{ matrix.python }}-${{ runner.os }}
          path: wheelhouse/*.whl

  commit:
    needs: [version, build]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/checkout@v4
        with:
          ref: wheelhouse
          path: wheelhouse

      - name: Create directory
        run: |
          mkdir -p wheelhouse/numpy
          mkdir -p wheelhouse/scipy

      - uses: actions/download-artifact@v4
        with:
          pattern: numpy-*
          path: wheelhouse/numpy
          merge-multiple: true

      - uses: actions/download-artifact@v4
        with:
          pattern: scipy-*
          path: wheelhouse/scipy
          merge-multiple: true

      - name: Update index
        run: |
          main/tools/make_index wheelhouse/numpy/ --package numpy
          main/tools/make_index wheelhouse/scipy/ --package scipy
          main/tools/link_pypi wheelhouse/

      - name: Commit wheels
        working-directory: wheelhouse
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
              echo "No changes to commit"
              exit 0
          fi
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "ci: Add wheels for ${{ inputs.package }}-${{ needs.version.outputs.package }}"
          git push origin HEAD:wheelhouse

...
# vim: set tw=98:
