name: Build wheels

on:
  workflow_dispatch:

jobs:
  versions:
    runs-on: ubuntu-latest

    outputs:
      numpy: ${{ env.NUMPY_VERSION }}

    steps:
      - name: Get latest releases
        id: get_versions
        run: |
          NUMPY_URL="https://api.github.com/repos/numpy/numpy/releases/latest"
          NUMPY_VERSION="$(curl -s "${NUMPY_URL}" | jq -r '.tag_name')"
          echo "NUMPY_VERSION=${NUMPY_VERSION}" >>$GITHUB_ENV

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019]
        python: [3.12]

    name: cp${{ matrix.python }} (${{ matrix.os }})

    needs: versions

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.x
          enable-cache: false

      - name: Install pkg-config (Windows)
        run: |
          choco install -y --no-progress --stoponfirstfailure                                    \
              --checksum 6004DF17818F5A6DBF19CB335CC92702 pkgconfiglite
        if: runner.os == 'windows'

      - name: Set python version
        run: |
          echo "UV_PYTHON=${{ matrix.python }}" >>$GITHUB_ENV
          echo "UV_PYTHON_PREFERENCE=only-managed" >>$GITHUB_ENV

          echo "NUMPY_DIR=${{ github.workspace }}/src" >>$GITHUB_ENV
          echo "MKL_DIR=${{ github.workspace }}/mkl" >>$GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out numpy source code
        uses: actions/checkout@v4
        with:
          repository: numpy/numpy
          ref: ${{ needs.versions.outputs.numpy }}
          path: ${{ env.NUMPY_DIR }}
          submodules: recursive

      - name: Install MKL libraries
        run: |
          export VIRTUAL_ENV="${{ env.MKL_DIR }}"
          uv venv "${VIRTUAL_ENV}"
          uv pip install mkl-devel

          # Get MKL version.
          echo "MKL_VERSION=$(uv pip show mkl | grep '^Version' | sed 's/Version: //')"          \
              >>$GITHUB_ENV

          # Get pkg-config path.
          if [[ "${{ runner.os }}" == "Linux" ]]; then
              source "${VIRTUAL_ENV}/bin/activate"
          else
              source "${VIRTUAL_ENV}/Scripts/activate"
          fi
          echo "PKG_CONFIG_PATH=$(python tools/get_file_in_pkg.py mkl-dynamic-ilp64-iomp.pc      \
              --pkg mkl-devel --parent)" >>$GITHUB_ENV

          # Fetch MKL license.
          cat $(python tools/get_file_in_pkg.py LICENSE.txt --pkg mkl-devel)                     \
              >>"${{ github.workspace }}/patches/LICENSE_MKL.txt"

      - name: Add MKL to runtime dependencies
        working-directory: ${{ env.NUMPY_DIR }}
        run: |
          # Pin runtime library to the exact version used for compiling.
          uv add --no-sync mkl=="${MKL_VERSION}" mkl-service

      - name: Add MKL licence
        working-directory: ${{ env.NUMPY_DIR }}
        run: |
          echo "" >>LICENSE.txt
          echo "----" >>LICENSE.txt
          echo "" >>LICENSE.txt
          cat LICENSES_bundled.txt >>LICENSE.txt
          cat "${{ github.workspace }}/patches/LICENSE_MKL.txt" >>LICENSE.txt

      - name: Apply patches
        run: |
          # Apply numpy patches
          cd "${{ env.NUMPY_DIR }}"
          git apply "${{ github.workspace }}"/patches/*.patch

          # Use single dynamic library (Hack)
          cp "${PKG_CONFIG_PATH}/mkl-sdl.pc" "${PKG_CONFIG_PATH}/mkl-dynamic-ilp64-iomp.pc"

          # Fix MKL pkg-config on Windows
          if [[ "${{ runner.os }}" == "Windows" ]]; then
              cp "${{ github.workspace }}"/patches/*.pc "${PKG_CONFIG_PATH}/"
          fi

      # TODO: add link time optimization flags once everything is working (-Db_lto)
      - name: Build numpy
        working-directory: ${{ env.NUMPY_DIR }}
        run: |
          [[ "${{ runner.os }}" == "Windows" ]] && vsenv='-Csetup-args=--vsenv'
          uv build --wheel ${vsenv}                                                              \
              -Csetup-args=-Dblas=mkl                                                            \
              -Csetup-args=-Dlapack=mkl                                                          \
              -Csetup-args=-Duse-ilp64=true                                                      \
              -Csetup-args=-Dmkl-threading=iomp                                                  \
              -Csetup-args=-Dallow-noblas=false

      - name: Repair wheel (Linux)
        working-directory: ${{ env.NUMPY_DIR }}/dist
        run: |
          uvx auditwheel repair *.whl -w . --exclude 'libmkl*' --plat manylinux_2_35_x86_64
          find . -type f -not -name "*manylinux*" -delete
        if: runner.os == 'linux'

      - name: Repair wheel (Windows)
        working-directory: ${{ env.NUMPY_DIR }}/dist
        run: |
          uvx delvewheel repair *.whl -w . --exclude 'mkl_rt.2.dll'
        if: runner.os == 'windows'

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: numpy-${{ needs.versions.outputs.numpy }}-cp${{ matrix.python }}-${{ runner.os }}
          path: ${{ env.NUMPY_DIR }}/dist/*.whl

  commit:
    needs: [versions, build]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: numpy-*
          path: wheelhouse
          merge-multiple: true

      - name: Commit wheels
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
              echo "No changes to commit"
              exit 0
          fi
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add wheelhouse
          git commit -m "ci: Add wheels for numpy-${{ needs.versions.outputs.numpy }}"
          git push origin ${{ github.ref_name }}:main

...
# vim: set tw=98:
